version: '3.7'

services:
  recipes-db:
    image: mariadb:10.2.32
    container_name: recipes-mariadb
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: <enter-your-root-password-here>
      MYSQL_USER: recipes_user
      MYSQL_PASSWORD: <enter-your-password-here>
    volumes:
      - recipes-data:/var/lib/mysql
      - ./resources/initdb:/docker-entrypoint-initdb.d:ro

  recipes-backend:
    build: .
    container_name: recipes-php
    working_dir: /var/www
    command: php -S 0.0.0.0:8080
    environment:
      - DB_SERVER=recipes-db
    ports:
      - 80:8080
    volumes:
      - .:/var/www
      - recipes-logs:/var/www/src/logs
    links:
      - recipes-db

volumes:
  recipes-logs:
  recipes-data:
